name: Update products

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SYNTHETIC_DATA_REPO_PAT }}
      - name: Update submodules to latest configured branches
        run: |
          git -C submodPath config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git submodule update --remote
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update submodules
