name: Update products

on:
  workflow_dispatch:
  schedule:
    - cron:  '9 9 * * 4'

jobs:
  update-submodules:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SYNTHETIC_DATA_REPO_PAT }}
      - name: Update submodules to latest configured branches
        run: |
          git submodule foreach '
            branch=$(git config -f $toplevel/.gitmodules submodule.$name.branch || echo HEAD)
            git config remote.origin.fetch +refs/heads/$branch:refs/remotes/origin/$branch
          '
          git submodule update --remote
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update submodules
          fetch: false
