name: Update products

on:
  schedule:
    - cron:  '7 7 * * 1' # Monday at 07:07 UTC
    - cron:  '7 7 * * 4' # Thursday at 07:07 UTC
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update submodules to latest configured branches
        run: |
          git submodule update --remote
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update submodules
